title: Zahabzze
email: sales@zahabzze.com
description: >-
  Zahabzze is the perfect store for all your furniture and appliance needs. We offer a vast catalog of items at very affordable prices! No more spending hours driving from store to store trying to find what you want. Now, you can find everything here at Zahabzze!
collections_dir: collections
collections:
  categories:
    output: true
  products:
    output: true

url: https://zahabzze.com.au
baseurl: /

sass:
  style: compact